# generated by build_frequency_lists.py
frequency_lists =
  passwords: "123456,password,12345678,qwerty,123456789,12345,1234,111111,1234567,dragon,123123,baseball,abc123,football,monkey,letmein,shadow,master,696969,michael,mustang,666666,qwertyuiop,123321,1234567890,pussy,superman,654321,1qaz2wsx,7777777,fuckyou,qazwsx,jordan,jennifer,123qwe,000000,killer,trustno1,hunter,harley,zxcvbnm,asdfgh,buster,andrew,batman,soccer,tigger,charlie,robert,sunshine,thomas,iloveyou,fuckme,ranger,daniel,hockey,george,computer,michelle,jessica,starwars,asshole,pepper,klaster,112233,zxcvbn,freedom,princess,joshua,maggie,pass,ginger,11111111,131313,fuck,amanda,ashley,love,cheese,159753,nicole,summer,matthew,chelsea,dallas,biteme,matrix,william,password123".split(",")
module.exports = frequency_lists
